preload = /home/ameera/.config/hypr/wallpaper/Brisbane_cityscape_6000x4000.jpeg
wallpaper = eDP-1,/home/ameera/.config/hypr/wallpaper/Brisbane_cityscape_6000x4000.jpeg
wallpaper = DP-2,/home/ameera/.config/hypr/wallpaper/Brisbane_cityscape_6000x4000.jpeg
wallpaper = DP-3,/home/ameera/.config/hypr/wallpaper/Brisbane_cityscape_6000x4000.jpeg
wallpaper = HDMI-A-1,/home/ameera/.config/hypr/wallpaper/Brisbane_cityscape_6000x4000.jpeg
